### ISSUE TITLE
Make RepoSense resilient to data overload

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1266]
We can make RepoSense more resilient to data overload problems. Some examples:
- [ ] large files
- [ ] long lines e.g., a minified file
- [ ] high number of filers per repo/author
- [ ] high number of commits

What we are trying to avoid are:
* Report not loading
* Certain pages freezing
* Report generation taking too long
* Report taking too much space

For each case, we can consider solutions such as,
* omit and proceed with the rest
* clip at a certain size
* warn users
* provide was to configure limits e.g., using flags

**Comment by anubh-v** [comment]
For the issue of "reports taking too much space", I have measured the file space saved when we remove whitespace from the JSON files. The measurements are in [this comment](https://github.com/reposense/RepoSense/issues/1227#issuecomment-667512152)

**Comment by chan-j-d** [comment]
I believe the first two points have been addressed by the https://github.com/reposense/RepoSense/pull/1647 and https://github.com/reposense/RepoSense/pull/1750.
