### ISSUE TITLE
Migrate entire frontend to TypeScript

### ISSUE THREAD

**Issue by vvidday** [reposense/RepoSense#1936]
### What feature(s) would you like to see in RepoSense

A completely TypeScript frontend.

### Is the feature request related to a problem?

As described in #1632, converting our frontend from JavaScript to TypeScript has many advantages, including type safety, better developer experience (intellisense etc), as well as making the codebase less confusing for new contributors (currently, there's many objects being passed around in the frontend that are of the `any` type, see #1632 for an example).

Even though TypeScript has been added in #1721, the frontend is still mostly JavaScript, including all our `.vue` files.

### If possible, describe the solution

We can start slowly converting the existing `.js` and `.vue` files to TypeScript. For `.vue` files, this can be done by adding `lang='ts'` to the `<template>` tag, wrapping the component with `defineComponent()`, and fixing all the errors that pop up.

While converting, we should be mindful of best practices, such as trying to avoid the use of `any` or `// @ts-ignore` except in cases where it is unavoidable. (Since using `any` defeats the purpose of using TypeScript in the first place.)

As this is a big task, it should be split up into multiple PRs.

### Additional context

#1903 has provided a decent starting point by typing the data that the frontend reads in from the `.json` files generated by the backend. This data is read/processed by the frontend components & passed between them. We can try to 'follow the path' of this data (e.g. `app.vue` -> `c-summary.vue` -> `c-summary-charts.vue` -> `c-zoom.vue`) and convert the files to TypeScript in order. i.e. we should focus on converting the parent components first.

### Main priority
- [x] `api.js` (all the global functions) - #1903 
- [x] `store.js` (Vuex store) - #1937 
- [x] `app.vue` (Root component) - #1938 
- [x] `c-summary.vue` - #1953 
- [x] `c-summary-charts.vue` - #1976
- [x] #1963
- [x] `c-authorship.vue` - #1969 

### Smaller files/components
- [x] `c-ramp.vue` (moved here as it is a smaller component compared to zoom/summary/authorship) #2037 
- [x] `c-segment.vue` #2035 
- [x] `c-segment-collection.vue` #2036
- [x] `c-resizer.vue` #2038
- [x] JS files in `utils` folder (`repo-sorter`, `ramp-colour-generator` etc) 
- [ ] #1946

**Comment by zhoukerrr** [comment]
@vvidday Thanks for listing the files out nicely here. I agree with the priority that you put here. @ckcherry23 Maybe the 2 of you can work on this together and see if we can get those under **Main priority** done by this semester?

**Comment by HCY123902** [comment]
Actually, the `cypress` files can also be migrated, although this may not have much value. What do you think

**Comment by vvidday** [comment]
> Actually, the `cypress` files can also be migrated, although this may not have much value. What do you think

Great point! I agree that there's not too much value (at least compared to migrating the actual frontend files), especially since a type error e.g. referencing a non-existent HTML attribute would probably result in a failing test (during assertion). But it would still be good to eventually migrate those over for consistency and it might catch some very edge/corner cases. I've added them to the list above!

However, as they are low priority as you mentioned, and also considering that the migration would be fairly straightforward, we could potentially separate it & label it as a good first issue for new contributors, as Prof mentioned today as well.

**Comment by HCY123902** [comment]
yeah sure. I have created a separate issue for this meant for those contributing for the first time

**Comment by chan-j-d** [comment]
Closing this issue as it has been completed with #2053 being the last PR that completes the migration for the frontend code
